# FORTIS Secrets Template
# Copy this file to secrets.yaml and fill in the actual values
# NEVER commit the actual secrets.yaml file to version control

# Database Secrets
DB_HOST: "your-database-host"
DB_PORT: "5432"
DB_NAME: "fortis"
DB_USERNAME: "fortis_user"
DB_PASSWORD: "your-secure-database-password"

# Redis Secrets
REDIS_HOST: "your-redis-host"
REDIS_PORT: "6379"
REDIS_PASSWORD: "your-secure-redis-password"

# JWT Secrets
JWT_SECRET: "your-super-secure-jwt-secret-key-minimum-32-characters"

# TSE API Secrets
TSE_API_KEY: "your-tse-api-key"
TSE_API_SECRET: "your-tse-api-secret"

# Blockchain Secrets
POLYGON_RPC_URL: "https://polygon-rpc.com"
POLYGON_PRIVATE_KEY: "your-polygon-private-key"
VOTING_CONTRACT_ADDRESS: "0x..."
AUDIT_CONTRACT_ADDRESS: "0x..."
IDENTITY_CONTRACT_ADDRESS: "0x..."
TOKEN_CONTRACT_ADDRESS: "0x..."

# Encryption Secrets
ENCRYPTION_KEY: "your-256-bit-encryption-key"

# AWS Secrets
AWS_ACCESS_KEY: "your-aws-access-key"
AWS_SECRET_KEY: "your-aws-secret-key"
AWS_REGION: "us-east-1"

# Email Secrets
EMAIL_SMTP_HOST: "smtp.gmail.com"
EMAIL_SMTP_PORT: "587"
EMAIL_USERNAME: "your-email@fortis.gov.br"
EMAIL_PASSWORD: "your-email-password"

# SMS Secrets
SMS_API_KEY: "your-sms-api-key"
SMS_API_SECRET: "your-sms-api-secret"

# Monitoring Secrets
PROMETHEUS_PASSWORD: "your-prometheus-password"
GRAFANA_PASSWORD: "your-grafana-password"

# Alerting Secrets
ALERT_WEBHOOK_URL: "https://hooks.slack.com/services/..."
SLACK_TOKEN: "your-slack-token"
DISCORD_WEBHOOK: "https://discord.com/api/webhooks/..."

# Third-party API Secrets
GOOGLE_MAPS_API_KEY: "your-google-maps-api-key"
TWILIO_ACCOUNT_SID: "your-twilio-account-sid"
TWILIO_AUTH_TOKEN: "your-twilio-auth-token"

# Certificate Secrets
SSL_CERT_PATH: "/etc/ssl/certs/fortis.crt"
SSL_KEY_PATH: "/etc/ssl/private/fortis.key"
CA_CERT_PATH: "/etc/ssl/certs/ca.crt"

# Biometric Secrets
BIOMETRIC_ENCRYPTION_KEY: "your-biometric-encryption-key"
FACIAL_RECOGNITION_API_KEY: "your-facial-recognition-api-key"

# AI/ML Secrets
OPENAI_API_KEY: "your-openai-api-key"
HUGGINGFACE_API_KEY: "your-huggingface-api-key"
OLLAMA_API_KEY: "your-ollama-api-key"

# Backup Secrets
BACKUP_ENCRYPTION_KEY: "your-backup-encryption-key"
BACKUP_PASSPHRASE: "your-backup-passphrase"

# Compliance Secrets
AUDIT_ENCRYPTION_KEY: "your-audit-encryption-key"
COMPLIANCE_API_KEY: "your-compliance-api-key"

# Development Secrets (for local development only)
DEV_DATABASE_URL: "postgres://fortis:fortis@localhost:5432/fortis_dev"
DEV_REDIS_URL: "redis://localhost:6379"
DEV_JWT_SECRET: "dev-jwt-secret-key"
DEV_ENCRYPTION_KEY: "dev-encryption-key"

# Testing Secrets (for testing only)
TEST_DATABASE_URL: "postgres://fortis:fortis@localhost:5432/fortis_test"
TEST_REDIS_URL: "redis://localhost:6379"
TEST_JWT_SECRET: "test-jwt-secret-key"
TEST_ENCRYPTION_KEY: "test-encryption-key"
