apiVersion: v1
kind: Namespace
metadata:
  name: fortis
  labels:
    name: fortis
    app: fortis-voting-system
    environment: production
    version: "1.0.0"
    managed-by: kubernetes
    part-of: fortis-ecosystem
  annotations:
    description: "Namespace principal do sistema FORTIS de votação eletrônica"
    contact: "fortis-team@tse.gov.br"
    version: "1.0.0"
    last-updated: "2025-12-15"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fortis-resource-quota
  namespace: fortis
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "50"
    configmaps: "50"
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fortis-limit-range
  namespace: fortis
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "10Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim
