apiVersion: v1
kind: Namespace
metadata:
  name: fortis
  labels:
    name: fortis
    app: fortis-voting-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fortis-quota
  namespace: fortis
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fortis-limits
  namespace: fortis
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
